project:
  type: website
  output-dir: website
  preview:
    port: 1111
    browser: true
    watch-inputs: true
  render: 
    - index.qmd
  resources:
    - src/
website:
  title: "ISOTYPE"
  favicon: img/favicon.ico
  navbar: false
format:
  html:
    theme: [style/style.scss]
    grid:
      body-width: 1000px
      margin-width: 380px
      gutter-width: 8px
    toc: false
    page-layout: article
    fontsize: 15px
    anchor-sections: false